### PR TITLE
Support .NET Framework 3.5

### PR DESCRIPTION
**Pull request by davidhunter22**
Add .NET Framework 3.5 support

### CODE REVIEW

**Comment by davidhunter22** [comment]
I think the checks are failing as the build machine doesn't have .NET 3.5 installed

**Comment by bgrainger** [comment]
> I think the checks are failing as the build machine doesn't have .NET 3.5 installed

Can that be fixed by installing `Microsoft.NETFramework.ReferenceAssemblies` on all platforms, including Windows? Or is there no way to build .NET 3.5 with CI?

**Comment by bgrainger** [comment]
How important is this? I'm curious how many people might be trying to use a recent C# compiler and trying to use C# 8.0 to target .NET 3.5.

**Comment by davidhunter22** [comment]
I'm not sure about how to fix it. I don't use GitHub for CI and know almost nothing about it. I will read up on it a bit.

**Comment by bgrainger** [comment]
I'm not able to build your fork locally (on Windows 10); I don't have .NET 3.5 installed at all. Adding the `Microsoft.NETFramework.ReferenceAssemblies` package doesn't seem to help.

The good news is that if I can figure out how to build it, CI should pass.
The bad news is that I can't currently build and ship an updated NuGet package for net35.

**Comment by davidhunter22** [comment]
OK, I'm assuming on a local development box you just install the .NET Framework 3.5 SDK.
I do this via the Visual Studio installer, 3.5 is an optional component.
Not sure it's possible to build without the relevant .NET Framework installed. 

I will try to build a "Hello World" project using GitHub actions with .NET 3.5. 
It does claim here https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md that
hosted runners have "Microsoft.Net.Component.3.5.DeveloperTools" tools installed but I'm not sure that is enough

**Comment by ash-hat** [comment]
Is there still interest in this feature? I was able to compile and use it locally on Linux after [a few tweaks](https://github.com/ash-hat/IndexRange/commit/65790af520f238818fea95e1509badd86375bfe5) (and deleting the signing properties, because I do not have the key). The main problem was that the version of [`Microsoft.NETFramework.ReferenceAssemblies`](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/) used in this project does not contain assemblies for `net35`. It seems that version 1.0.1, the version that contains the necessary assemblies, was released after this PR died out.

**Comment by bgrainger** [comment]
> The main problem was that the version of Microsoft.NETFramework.ReferenceAssemblies used in this project does not contain assemblies for net35. It seems that version 1.0.1, the version that contains the necessary assemblies, was released after this PR died out.

Thanks for making me aware of this; as per the above comments I was blocked on the inability to build the PR. I'll take another look.

> because I do not have the key

It's not secret: https://github.com/bgrainger/IndexRange/blob/master/IndexRange.snk

(But maybe signing still isn't supported on Linux yet?)

**Comment by bgrainger** [comment]
@ash-hat Thanks for your helpful comment. A version with your changes is available; please see https://github.com/bgrainger/IndexRange/issues/5#issuecomment-901408784.

**Comment by ash-hat** [comment]
> It's not secret

Ah. I haven't signed assemblies before so I thought it was some form of asymmetric cryptography and that's why it was giving me an error. Seems you found the signing issue I was having anyway, but maybe next time I shouldn't comment at 4am :sweat_smile:

**Pull request merged**
